### ISSUE TITLE
Fix BUNDLE_CACH_PATH

### ISSUE THREAD

**Issue by metaskills** [rails-lambda/lamby-cookiecutter#23]

**Comment by metaskills** [comment]
Done in latest cookiecutter. New docs available too. https://lamby.custominktech.com/

**Comment by tappleby** [comment]
I am still seeing BUNDLE_CACH_PATH in this repo, should these be updated to BUNDLE_CACHE_PATH?

**Comment by metaskills** [comment]
Whoops, fixed. Can you do a test create and deploy to see if that work and did not break anything?
